// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuqwv5skM8qSd2XMFNyc3wlWTmibY7bh0',
    appId: '1:385422170884:web:a5be74fa60e32c2f644e51',
    messagingSenderId: '385422170884',
    projectId: 'bita-zonemaster',
    authDomain: 'bita-zonemaster.firebaseapp.com',
    storageBucket: 'bita-zonemaster.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuw9YV0X8hxQ09D_UAaxnapaLQUQgtb-c',
    appId: '1:385422170884:android:ccae49d2bd950774644e51',
    messagingSenderId: '385422170884',
    projectId: 'bita-zonemaster',
    storageBucket: 'bita-zonemaster.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdOFN7kSW62bXbI4y4PBlz8zjkutvVIsE',
    appId: '1:385422170884:ios:08e1f2b1a95a23d7644e51',
    messagingSenderId: '385422170884',
    projectId: 'bita-zonemaster',
    storageBucket: 'bita-zonemaster.firebasestorage.app',
    iosBundleId: 'com.example.testappbita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdOFN7kSW62bXbI4y4PBlz8zjkutvVIsE',
    appId: '1:385422170884:ios:08e1f2b1a95a23d7644e51',
    messagingSenderId: '385422170884',
    projectId: 'bita-zonemaster',
    storageBucket: 'bita-zonemaster.firebasestorage.app',
    iosBundleId: 'com.example.testappbita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuqwv5skM8qSd2XMFNyc3wlWTmibY7bh0',
    appId: '1:385422170884:web:fc05576b7ff66a51644e51',
    messagingSenderId: '385422170884',
    projectId: 'bita-zonemaster',
    authDomain: 'bita-zonemaster.firebaseapp.com',
    storageBucket: 'bita-zonemaster.firebasestorage.app',
  );

}